#!/bin/bash
# void-install-script general library for things that are expected to be used multiple times

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\e[1;33m'
NC='\033[0m'

die() {
    echo -e "${RED}$commandFailure${NC}\nInstallation will not proceed." && exit 1
}

drawDialog() {
    dialog --stdout --cancel-label "Skip" --no-mouse --backtitle "https://github.com/kkrruumm/void-install-script" "$@"
}

diskCalculator() {
    diskOperand=$(echo $sizeInput | sed 's/G//g')
    diskFloat=$(echo $diskFloat - $diskOperand | bc)
    diskAvailable=$(echo $diskFloat - 0.5 | bc)
    diskAvailable+="G"

    if [ "$diskFloat" -lt 0 ]; then
        clear
        echo -e "${RED}Used disk space cannot exceed the maximum capacity of the chosen disk. Have you over-provisioned your disk? ${NC}\n"
        read -p "Press Enter to start disk configuration again." </dev/tty
        diskConfig
    fi

    return 0
}

partitionerOutput() {
    echo -e "Disk: $diskInput"
    echo -e "Disk size: $diskSize"
    echo -e "Available disk space: $diskAvailable \n"

    return 0
}

checkModule() {
    # Past this, I'm going to leave verifying correctness to the author of the module.
    # Check that relevant stuff is even in the file:
    local line t=0 s=0 d=0 m=0

    while read -r line; do
        [[ $line =~ title= ]] && t=1
        [[ $line =~ status=(on|off) ]] && s=1
        [[ $line =~ description= ]] && d=1
        [[ $line =~ main\(\) ]] && m=1

        # break out early if all flags are satisfied (should always happen in the top 3-4 lines of the module probably)
        (( t && s && d && m )) && break
    done < "modules/${i}"

    # if any flag is 0, the module failed the vibe check
    (( t && s && d && m )) || return 1

    # test for early failures such as the module requiring a username
    . "modules/$i" || return 1
    return 0
}

install() {
    xbps-install -Sy -R "$repository" -r /mnt "$@" || die
}

system() {
    chroot /mnt /bin/bash -c "$@" || die
}

setKernelParam() {
    case "$bootloader" in
        grub)
            sed -i -e "s:loglevel=4:loglevel=4 $1:" /mnt/etc/default/grub || die
        ;;
        uki)
            sed -i -e "s:loglevel=4:loglevel=4 $1:" /mnt/etc/kernel.d/post-install/60-ukify || die
        ;;
        zfsbootmenu)
            # this variable should empty once it goes out of scope
            # no need to explicitly unset to prevent dupes
            local zfsparams=$(zfs get -H -o value org.zfsbootmenu:commandline zroot/ROOT)
            zfs set org.zfsbootmenu:commandline="$zfsparams $1" zroot/ROOT || die
        ;;
    esac

    kernelparam_update="true"

    return 0
}

enableService() {
    # looping this will enable one to enableService service1 service2 service3...
    for service in "$@"; do
        system "ln -s /etc/sv/$service /var/service"
    done

    return 0
}
