#!/bin/bash
title=amdgpu_unlock
description="- Enables amdgpu overclocking"
status=off

main() {
    commandFailure="Enabling amdgpu overclocking has failed."
    case "$bootloader" in
        grub)
             sed -i -e 's/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 amdgpu.ppfeaturemask=0xffffffff/g' || die
             chroot /mnt /bin/bash -c "update-grub" || die
        ;;
        uki)
            sed -i -e 's/loglevel=4/loglevel=4 amdgpu.ppfeaturemask=0xffffffff/g' /mnt/etc/kernel.d/post-install/60-ukify || die
            chroot /mnt /bin/bash -c 'xbps-reconfigure -f linux"$(find /boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -f1,2 -d".")"' || die
        ;;
    esac

    return 0
}
