#!/bin/bash
title=apcupsd
description="- APC UPS Daemon"
status=off

main() {
    commandFailure="apcupsd installation has failed." &&
        install apcupsd

    commandFailure="Enabling apcupsd has failed." &&
        enableService apcupsd

    return 0
}
