#!/bin/bash
title=chrony
description="- Chrony NTP Daemon"
status=on

main() {
    install chrony ||
        { commandFailure="Chrony installation has failed." ; die ; }

    chroot /mnt /bin/bash -c "ln -s /etc/sv/chronyd /var/service" ||
        { commandFailure="Enabling chronyd has failed." ; die ; }

    return 0
}
