#!/bin/bash
title=chrony
description="- Chrony NTP Daemon"
status=on

main() {
    commandFailure="Chrony installation has failed." &&
        install chrony

    commandFailure="Enabling chronyd has failed." &&
        enableService chronyd

    return 0
}
