#!/bin/bash
title=cpu-ucode
description="- Installs CPU microcode for Intel or AMD"
status=off

main() {
    commandFailure="Installing CPU microcode package has failed."
    if lscpu | grep "GenuineIntel" ; then
        install void-repo-nonfree || die
        xmirror -s "$repository" -r /mnt || die
        install intel-ucode || die
        chroot /mnt /bin/bash -c 'xbps-reconfigure -f linux"$(find /boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -f1,2 -d".")"' || die
    elif lscpu | grep "AuthenticAMD" ; then
        # This package should already be installed as a dep. of linux-base, but just incase something changes:
        install linux-firmware-amd || die
    fi

    return 0
}
