#!/bin/bash

# Don't populate unless a user actually exists
[ -z "$username" ] && return 1

title=esync
description="- Enables esync by raising ulimit"
status=off

main() {
    echo "$username hard nofile 524288" >> /mnt/etc/security/limits.conf ||
        { commandFailure="Enabling esync has failed." ; die ; }

    return 0
}
