#!/bin/bash

# Don't populate unless a user actually exists
[ -z "$username" ] && return 0

title=esync
description="- Enables esync by raising ulimit"
status=off

main() {
    if [ -n "$username" ]; then
        echo "$username hard nofile 524288" >> /mnt/etc/security/limits.conf ||
            { commandFailure="Enabling esync has failed." ; die ; }
    fi

    return 0
}
