#!/bin/bash
title=flatpak
description="- Includes Flathub repository"
status=off

main() {
    install flatpak ||
        { commandFailure="Flatpak installation has failed." ; die ; }

    chroot /mnt /bin/bash -c "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo" ||
        { commandFailure="Adding flatpak repository has failed." ; die ; }

    return 0
}
