#!/bin/bash
title=flatpak
description="- Includes Flathub repository"
status=off

main() {
    commandFailure="Flatpak installation has failed." &&
        install flatpak

    commandFailure="Adding flatpak repository has failed." &&
        system "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"

    return 0
}
