#!/bin/bash
title=harden_proc
description="- Hardens /proc by setting hidepid=2 and gid=proc"
status=off

main() {
    echo "mount -o remount,rw,nosuid,nodev,noexec,relatime,hidepid=2,gid=proc /proc" >> /mnt/etc/rc.local ||
        { commandFailure="Modifying rc for hideproc has failed." ; die ; }

    chroot /mnt /bin/bash -c "groupadd proc" ||
        { commandFailure="Creating group for proc users has failed." ; die ; }

    if [ -n "$createUser" ]; then
        chroot /mnt /bin/bash -c "usermod -aG proc $username" ||
            { commandFailure="Adding user to proc group has failed." ; die ; }
    fi
    
    # Required for certain things the installer may deploy to function out of the box.
    if grep "polkitd" /mnt/etc/passwd ; then
        chroot /mnt /bin/bash -c "usermod -aG proc polkitd" ||
            { commandFailure="Adding polkit user to proc group has failed." ; die ; }
    fi

    if grep "gdm" /mnt/etc/passwd ; then
        chroot /mnt /bin/bash -c "usermod -aG proc gdm" ||
            { commandFailure="Adding gdm user to proc group has failed." ; die ; }
    fi

    return 0
}
