#!/bin/bash

[ "$filesystem" == "zfs" ] && return 1

title=init_on_free
description="- Enables init_on_free kernel parameter"
status=off

main() {
    commandFailure="Enabling init_on_free has failed."
    setKernelParam "init_on_free=1"

    return 0
}
