#!/bin/bash
title=init_on_free
description="- Enables init_on_free kernel parameter"
status=off

main() {
    commandFailure="Enabling init_on_free has failed."
    case "$bootloader" in
        grub)
            sed -i -e 's/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 init_on_free=1/g' /mnt/etc/default/grub || die
            chroot /mnt /bin/bash -c "update-grub" || die
        ;;
        uki)
            sed -i -e 's/loglevel=4/loglevel=4 init_on_free=1/g' /mnt/etc/kernel.d/post-install/60-ukify || die
            chroot /mnt /bin/bash -c 'xbps-reconfigure -f linux"$(find /boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -f1,2 -d".")"' || die
        ;;
    esac

    return 0
}
