#!/bin/bash
title=nftables
description="- Includes a default firewall config"
status=on

main() {
    commandFailure="nftables installation has failed." &&
        install nftables

    commandFailure="Configuring nftables firewall has failed."

    echo -e '#!/usr/sbin/nft -f \n' >> /mnt/etc/nftables.conf || die
    echo -e 'flush ruleset \n' >> /mnt/etc/nftables.conf || die

    # Create table
    system "nft add table inet filter"

    # Input chain
    system "nft add chain inet filter input '{type filter hook input priority 0; policy drop;}' &&
    nft add rule inet filter input ct state invalid drop &&
    nft add rule inet filter input ct state { established, related } accept &&
    nft add rule inet filter input iif "lo" accept &&
    nft add rule inet filter input iif != "lo" ip daddr 127.0.0.1/8 drop &&
    nft add rule inet filter input iif != "lo" ip6 daddr ::1 drop"

    # Output chain
    system "nft add chain inet filter output '{type filter hook output priority 0; policy accept;}'"

    # Forward chain 
    system "nft add chain inet filter forward '{type filter hook forward priority 0; policy drop;}'"

    # Save config
    commandFailure="Saving nftables config has failed." &&
        system "nft list ruleset >> /etc/nftables.conf"

    commandFailure="Enabling nftables has failed." &&
        system "ln -s /etc/sv/nftables /var/service"

    return 0
}
