#!/bin/bash
title=nftables
description="- Includes a default firewall config"
status=on

main() {
    install nftables ||
        { commandFailure="nftables installation has failed." ; die ; }

    commandFailure="Setting up nftables config has failed."

    echo -e '#!/usr/sbin/nft -f \n' >> /mnt/etc/nftables.conf || die
    echo -e 'flush ruleset \n' >> /mnt/etc/nftables.conf || die

    # Create table
    chroot /mnt /bin/bash -c "nft add table inet filter" || die

    # Input chain
    chroot /mnt /bin/bash -c "nft add chain inet filter input '{type filter hook input priority 0; policy drop;}' &&
    nft add rule inet filter input ct state invalid drop &&
    nft add rule inet filter input ct state { established, related } accept &&
    nft add rule inet filter input iif "lo" accept &&
    nft add rule inet filter input iif != "lo" ip daddr 127.0.0.1/8 drop &&
    nft add rule inet filter input iif != "lo" ip6 daddr ::1 drop" || die

    # Output chain
    chroot /mnt /bin/bash -c "nft add chain inet filter output '{type filter hook output priority 0; policy accept;}'" || die

    # Forward chain 
    chroot /mnt /bin/bash -c "nft add chain inet filter forward '{type filter hook forward priority 0; policy drop;}'" || die

    # Save config
    chroot /mnt /bin/bash -c "nft list ruleset >> /etc/nftables.conf" ||
        { commandFailure="Saving nftables config has failed." ; die ; }

    chroot /mnt /bin/bash -c "ln -s /etc/sv/nftables /var/service" ||
        { commandFailure="Enabling nftables has failed." ; die ; }

    return 0
}
