#!/bin/bash
title=noto-fonts
description="- Noto TTF fonts typically used by websites"
status=off

main() {
    commandFailure="Noto TTF fonts installation has failed." &&
        install noto-fonts-ttf noto-fonts-cjk

    return 0
}
