#!/bin/bash
title=openntpd
description="- OpenNTPD NTP Daemon"
status=off

main() {
    commandFailure="OpenNTPD installation has failed."
    echo -e "Installing OpenNTPD... \n"
    xbps-install -Sy -R $installRepo -r /mnt openntpd || failureCheck
    echo -e "OpenNTPD has been installed. \n"

    commandFailure="Enabling OpenNTPD has failed."
    echo -e "Enabling OpenNTPD... \n"
    chroot /mnt /bin/bash -c "ln -s /etc/sv/openntpd /var/service" || failureCheck
    echo -e "OpenNTPD has been enabled. \n"

    return 0
}
