#!/bin/bash
title=socklog
description="- Enables system logging"
status=on

main() {
    commandFailure="Socklog installation has failed." &&
        install socklog-void

    commandFailure="Enabling socklog has failed." &&
        system "ln -s /etc/sv/socklog-unix /var/service && ln -s /etc/sv/nanoklogd /var/service"

    return 0
}
