#!/bin/bash
title=socklog
description="- Enables system logging"
status=on

main() {
    install socklog-void ||
        { commandFailure="Socklog installation has failed." ; die ; }

    chroot /mnt /bin/bash -c "ln -s /etc/sv/socklog-unix /var/service && ln -s /etc/sv/nanoklogd /var/service" ||
        { commandFailure="Enabling socklog has failed." ; die ; }

    return 0
}
