#!/bin/bash
title=socklog
description="- Enables system logging"
status=on

main() {
    install socklog-void ||
        { commandFailure="Socklog installation has failed." ; die ; }

    commandFailure="Enabling socklog has failed." &&
        system "ln -s /etc/sv/socklog-unix /var/service && ln -s /etc/sv/nanoklogd /var/service"

    return 0
}
