#!/bin/bash
title=sof-firmware
description="- Sound Open Firmware and topology binaries (Audio support for modern laptops)"
status=off

main() {
    commandFailure="SOF Firmware installation has failed." &&
        install sof-firmware

    return 0
}
