#!/bin/bash
title=tlp
description="- Advanced power management"
status=off

main() {
    install tlp ||
        { commandFailure="tlp installation has failed." ; die ; }

    commandFailure="Enabling tlp has failed." &&
        system "ln -s /etc/sv/tlp /var/service"

    return 0
}
