#!/bin/bash
title=tlp
description="- Advanced power management"
status=off

main() {
    install tlp ||
        { commandFailure="tlp installation has failed." ; die ; }

    chroot /mnt /bin/bash -c "ln -s /etc/sv/tlp /var/service" ||
        { commandFailure="Enabling tlp has failed." ; die ; }

    return 0
}
