#!/bin/bash
title=tlp
description="- Advanced power management"
status=off

main() {
    commandFailure="tlp installation has failed." &&
        install tlp

    commandFailure="Enabling tlp has failed." &&
        enableService tlp

    return 0
}
