#!/bin/bash
title=usbguard
description="- Installs and enables usbguard, allows current devices"
status=off

main() {
    commandFailure="Installing usbguard has failed." &&
        install usbguard

    commandFailure="Configuring usbguard has failed." &&
        system "usbguard generate-policy > /etc/usbguard/rules.conf"

    commandFailure="Enabling usbguard has failed." &&
        system "ln -s /etc/sv/usbguard /var/service"

    return 0
}
