#!/bin/bash
title=usbguard
description="- Installs and enables usbguard, allows current devices"
status=off

main() {
    install usbguard ||
        { commandFailure="Installing usbguard has failed." ; die ; }

    chroot /mnt /bin/bash -c "usbguard generate-policy > /etc/usbguard/rules.conf" ||
        { commandFailure="Configuring usbguard has failed." ; die ; }

    chroot /mnt /bin/bash -c "ln -s /etc/sv/usbguard /var/service" ||
        { commandFailure="Enabling usbguard has failed." ; die ; }

    return 0
}
