#!/bin/bash
title=wifi-firmware
description="- Wifi firmware and utilities"
status=on

# If this is toggled off, and the user is using the regular base metapackage,
# the packages will be removed from the system.
# If the user has defined their own basesystem, install if enabled:
main() {
    [ "$basesystem" != "base-system" ] &&
        { commandFailure="Wifi firmware and utility installation has failed." ; install iw wpa_supplicant wifi-firmware ; }

    return 0
}
