#!/bin/bash
title=xtools
description="- Installs xtools package for working with xbps"
status=on

main() {
    commandFailure="Installing xtools package has failed." &&
        install xtools

    return 0
}
