#!/bin/bash

[ -n "$graphicsArray" ] &&
    commandFailure="Graphics driver installation has failed."

for i in "${graphicsArray[@]}"
do
    case $i in
        amd)
            install mesa-dri vulkan-loader mesa-vulkan-radeon mesa-vaapi mesa-vdpau
        ;;

        amd-32bit)
            install void-repo-multilib
            xmirror -s "$repository" -r /mnt || die
            install libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit mesa-dri-32bit
        ;;

        nvidia)
            install void-repo-nonfree
            xmirror -s "$repository" -r /mnt || die
            install nvidia

            # Enable mode setting for wayland compositors
            # This default should change to drm enabled with more recent nvidia drivers, expect this to be removed in the future.
            setKernelParam "nvidia_drm.modeset=1"
        ;;

        nvidia-32bit)
            install void-repo-multilib-nonfree void-repo-multilib
            xmirror -s "$repository" -r /mnt || die
            install nvidia-libs-32bit
        ;;

        intel)
            install mesa-dri vulkan-loader mesa-vulkan-intel intel-video-accel
        ;;

        intel-32bit)
            install void-repo-multilib
            xmirror -s "$repository" -r /mnt || die
            install libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit mesa-dri-32bit
        ;;

        nvidia-nouveau)
            install mesa-dri mesa-nouveau-dri
        ;;

        nvidia-nouveau-32bit)
            install void-repo-multilib
            xmirror -s "$repository" -r /mnt || die
            install libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit mesa-dri-32bit mesa-nouveau-dri-32bit
        ;;

        *)
            echo "Continuing without graphics drivers..."
        ;;

    esac
done

[ -n "$network" ] && [ "$network" != "none" ] &&
    commandFailure="DHCP client setup has failed."

case "$network" in
    NetworkManager)
        install NetworkManager
        system "ln -s /etc/sv/NetworkManager /var/service"
    ;;
    dhcpcd)
        system "ln -s /etc/sv/dhcpcd /var/service"
    ;;
esac

setup_greetd() {
    install greetd
    system "ln -s /etc/sv/greetd /var/service"
    cp misc/greetd-run /mnt/usr/local/bin/"${desktop}"-run || die
    sed -i 's,command = "agreety --cmd /bin/sh",command = "agreety --cmd '"${desktop}"'-run",' /mnt/etc/greetd/config.toml || die

    # this defaults to 'sway' only because it applies to both sway and swayfx
    if [ "$desktop" != 'sway' ] && [ "$desktop" != 'swayfx' ]; then
        sed -i "s/sway/${desktop}/g" /mnt/usr/local/bin/"${desktop}"-run || die
    fi

    system "chown root:root /usr/local/bin/${desktop}-run"
    system "chmod 755 /usr/local/bin/${desktop}-run"
    system "chmod +x /usr/local/bin/${desktop}-run"
}

[ -n "$desktop" ] && [ "$desktop" != "none" ] &&
    commandFailure="GUI installation has failed"

case "$desktop" in
    gnome)
        install gnome-core gnome-console gnome-tweaks gnome-browser-connector gnome-text-editor xdg-user-dirs xorg-minimal xorg-video-drivers
        system "ln -s /etc/sv/gdm /var/service"
    ;;
    kde)
        install kde-plasma kde-baseapps xdg-user-dirs xorg-minimal xorg-video-drivers
        system "ln -s /etc/sv/sddm /var/service"
    ;;
    xfce)
        install xfce4 xfce4-pulseaudio-plugin lightdm lightdm-gtk3-greeter xorg-minimal xdg-user-dirs xorg-fonts xorg-video-drivers

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        system "ln -s /etc/sv/lightdm /var/service"
    ;;
    sway)
        install sway elogind polkit polkit-elogind foot xorg-fonts xdg-desktop-portal-wlr xdg-user-dirs

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        system "ln -s /etc/sv/polkitd /var/service"

        if [ "$greetd" == "Yes" ]; then
            setup_greetd
            echo 'exec dbus-run-session sway "$@"' >> /mnt/usr/local/bin/"${desktop}"-run || die
        fi
    ;;
    swayfx)
        install swayfx elogind polkit polkit-elogind foot xorg-fonts xdg-desktop-portal-wlr xdg-user-dirs

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        system "ln -s /etc/sv/polkitd /var/service"

        if [ "$greetd" == "Yes" ]; then
            setup_greetd
            echo 'exec dbus-run-session sway "$@"' >> /mnt/usr/local/bin/"${desktop}"-run || die
        fi
    ;;
    river)
        install river elogind polkit polkit-elogind foot xorg-fonts xdg-desktop-portal-wlr xdg-user-dirs

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        system "ln -s /etc/sv/polkitd /var/service"

        if [ "$greetd" == "Yes" ]; then
            setup_greetd
            echo 'exec dbus-run-session river "$@"' >> /mnt/usr/local/bin/"${desktop}"-run || die
        fi
    ;;
    i3)
        install i3 xorg-minimal xinit xterm xorg-fonts xorg-video-drivers xdg-user-dirs

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        if [ "$lightdm" == "Yes" ]; then
            install lightdm lightdm-gtk3-greeter
            system "ln -s /etc/sv/lightdm /var/service"
        fi
    ;;
    niri)
        install niri elogind polkit polkit-elogind alacritty fuzzel xorg-fonts xdg-desktop-portal-gtk xdg-desktop-portal-gnome xdg-user-dirs

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        system "ln -s /etc/sv/polkitd /var/service"

        if [ "$greetd" == "Yes" ]; then
            setup_greetd
            echo 'exec dbus-run-session niri --session "$@"' >> /mnt/usr/local/bin/"${desktop}"-run || die
        fi
    ;;
    wayfire)
        install wayfire elogind polkit polkit-elogind alacritty xorg-fonts xdg-desktop-portal-wlr xdg-user-dirs

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        system "ln -s /etc/sv/polkitd /var/service"

        if [ "$greetd" == "Yes" ]; then
            setup_greetd
            echo 'exec dbus-run-session wayfire "$@"' >> /mnt/usr/local/bin/"${desktop}"-run || die
        fi
    ;;
    mate)
        install mate mate-terminal lightdm lightdm-gtk3-greeter xorg-minimal xdg-user-dirs xorg-fonts xorg-video-drivers

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        system "ln -s /etc/sv/lightdm /var/service"
    ;;
esac

[ -n "$audio" ] && [ "$audio" != "none" ] &&
    commandFailure="Audio server installation has failed."

case "$audio" in
    pipewire)
        install pipewire alsa-pipewire wireplumber
        mkdir -p /mnt/etc/alsa/conf.d || die
        mkdir -p /mnt/etc/pipewire/pipewire.conf.d || die

        # this is now required to start pipewire and its session manager 'wireplumber' in an appropriate order, this should achieve a desireable result system-wide
        system "ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/"
        system "ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/"

        # enable pipewire and pipewire-pulse autostart
        if [ -e "/usr/share/applications/pipewire.desktop" ] && [ -e "/etc/xdg/autostart/" ]; then
            system "ln -s /usr/share/applications/pipewire.desktop /etc/xdg/autostart/pipewire.desktop"
            system "ln -s /usr/share/applications/pipewire-pulse.desktop /etc/xdg/autostart/pipewire-pulse.desktop"
        fi

        # alsa configuration
        system "ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /etc/alsa/conf.d"
        system "ln -s /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d"
    ;;
    pulseaudio)
        install pulseaudio alsa-plugins-pulseaudio
    ;;
esac

return 0
